import { Metadata } from "next";
import "./globals.css";
import ErrorWrapper from "./error-wrapper";

export const metadata: Metadata = {
  title: {
    default: "Next.js Tutorial - Codevolution",
    template: "%s | Codevolution",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex min-h-screen flex-col bg-black dark:text-white">
        <header className="sticky start-0 top-0 z-20 w-full border-b border-neutral-200 bg-white p-[1rem] dark:border-neutral-600 dark:bg-black">
          <p className="text-2xl font-bold text-white">Header</p>
        </header>
        <div className="flex min-h-[calc(100vh-8.5rem)] flex-col items-center justify-center">
          <ErrorWrapper>{children}</ErrorWrapper>
        </div>
        <footer className="mt-auto w-full border-t border-neutral-200 bg-white p-[1rem] dark:border-neutral-600 dark:bg-black">
          <p className="text-2xl font-bold text-white">Footer</p>
        </footer>
      </body>
    </html>
  );
}
